### PR TITLE
Relational schema documentation added

### PR DESCRIPTION
**Pull request by Zibilyonik**
The schema for the project's data structure has been added to the docs file along with the auto-generated SQL code for the aforementioned schema

### CODE REVIEW

**Comment by Zibilyonik** [comment]
I have noticed that I will have to create the diagram as well, and I will do so on Friday. If you are going to request changes due to that, you don't have to mention anything extra. For now, I have created the schema only and it would help if you could give some feedback on it.

**Review by suretrust — CHANGES_REQUESTED** [review]
Hi team, 👋 

### You are off to a great start! 💯 Just a few suggestions. 👇 

- [x] It's hard to read the relationship between the models from your diagram. You can use the right tools (e.g: [lucidchart](https://www.lucidchart.com/pages/er-diagrams)) to draw your ERD and read about how to draw it properly. ([How to part one](https://www.youtube.com/watch?v=QpdhBUYk7Kk), [how to part two](https://www.youtube.com/watch?v=-CuY5ADwn24&vl=en))
* [x] Make sure that Primary Keys (PK) and Foreign Keys (FK) are assigned correctly
* [x] Friendship table has `status` or `confirmed` column ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone1/status.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
* [x] User table has `image_link` column ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone1/imglink.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

**Kindly submit for another CRR once these issues have been resolved.** _Happy coding!_ 🎉

**Comment by Zibilyonik** [comment]
> Hi team, 👋
> 
> ### You are off to a great start! 💯 Just a few suggestions. 👇
> * [x]  It's hard to read the relationship between the models from your diagram. You can use the right tools (e.g: [lucidchart](https://www.lucidchart.com/pages/er-diagrams)) to draw your ERD and read about how to draw it properly. ([How to part one](https://www.youtube.com/watch?v=QpdhBUYk7Kk), [how to part two](https://www.youtube.com/watch?v=-CuY5ADwn24&vl=en))
> 
> * [x]  Make sure that Primary Keys (PK) and Foreign Keys (FK) are assigned correctly
> * [x]  Friendship table has `status` or `confirmed` column ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone1/status.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
> * [x]  User table has `image_link` column ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone1/imglink.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
> 
> **Kindly submit for another CRR once these issues have been resolved.** _Happy coding!_ 🎉

The image presented is the relational schema, not the diagram, but you can still see on the schema that the status column for the friendship requests is present and keys have been assigned properly to identify the users and the posts, and connect all the components together.

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @Zibilyonik     
#### Great Job so far, but there are a few more things required. 
### General
 - [x] Lets activate linter for this project.
- [x] Lets change the name of Friends to Friendship.
- [x] The content of  Friendship should be `user_id` , `friend_id` and `status` should be included.
- [x] Comment: `post_id` should be `FK`

### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by Zibilyonik** [comment]
> ## Hi @Zibilyonik 
> #### Great Job so far, but there are a few more things required.
> ### General
> * [x]  Lets activate linter for this project.
> * [x]  Lets change the name of Friends to Friendship.
> * [x]  The content of  Friendship should be `user_id` , `friend_id` and `status` should be included.
> * [x]  Comment: `post_id` should be `FK`
> 
> ### Make changes and submit another code review request.
> _Happy coding_
> (Any questions Feel free to contact me on slack @kobiyoyo)

Please tell me where it mentions that that specific table must be named "Friendship". I don't understand how the name of the table or the columns can affect my project negatively, nor do I see any suggestion on the project page stating that I should use those names specifically.

**Review by kobiyoyo — APPROVED** [review]
# Project Approved :thumbsup:
## Hello @Zibilyonik ,  You have done a great job with this project. :clap:
#### You can go ahead and merge !!!

**Pull request merged**
