### PR TITLE
Friendships with 2 rows implemented

### PR DESCRIPTION
**Pull request by Zibilyonik**
All requests for advanced friendship features with 2 rows for mutual friendship has been completed.

### CODE REVIEW

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hello! Impressive work on this milestone:+1:. Here are the things you need to attend to now:**

:point_right: Fix your lint errors

:point_right: Like you have in your ERD, for an efficient implementation you should add a status or confirmed column (bolean) to your friendships table to keep track of the status of friendship.

:point_right: With the status column, you should have a model method in friendship model that updates the status on friendship confirmation and creates the reverse friendship in db.

:point_right: A users friends can then be retrieved with an association like this:
```ruby
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships

```

:point_right: Pending friends can be retrieved with an association like this:
```ruby
# User model

# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```

:point_right: and friend requests can be retrieved with an association like this one:
```ruby
# User model

# Users who requested to be friends (needed for notifications)
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
```

:point_right: **_users index_** should display user names with appropriate friendship buttons (Add friend for users who are not friends yet)




:point_right: Post index shouldn't display all posts. It should display the current user's posts and his friends' posts only.



:point_right: You can remove empty view files, especially in the friendships folder.

:exclamation:Important - You should add unit tests for your model methods and validations and integration tests for your features.


_**Kindly make these changes and submit another code review request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

**Comment by Zibilyonik** [comment]
Stylelint errors are from Microverse scaffolding, so they're not related to my project. For rubocop errors, I've been unable to find a solution to them so if you can give me a hand with it I would appreciate it.

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello Team!
### Good job you have shown :clap: now fix the rubocop errors, seek help if you are unable.
### Make the changes and submit for another code review. Good luck!

By Raymond
slack @iamraymond

**Comment by Zibilyonik** [comment]
> Stylelint errors are from Microverse scaffolding, so they're not related to my project. For rubocop errors, I've been unable to find a solution to them so if you can give me a hand with it I would appreciate it.

The Rubocop errors are fixed, bu stylelint errors from the scaffolding still exist.

**Review by wathigo — APPROVED** [review]
### Approved :heavy_check_mark: 
Great work @Zibilyonik 

Sure, the errors are coming from the scaffold.

**You may proceed to the next milestone.**

**Happy Coding :computer: 
Simon Wathigo.**

**Pull request merged**
