### PR TITLE
Project completed and ready for heroku deployment

### PR DESCRIPTION
**Pull request by Zibilyonik**

### CODE REVIEW

**Review by suretrust — COMMENTED** [review]
HI @Zibilyonik, 👋 

### Great job thus far. 🙌 Please see my comments. 👇 

- [x] You should not merge until your PR is approved.
* [x] Link to Heroku is not added to your readME file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/heroku.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

- [x] Fix all linter errors.

**Kindly submit another CRR once these issues have been fixed.** _Happy coding!_ 🎉

**Comment by Zibilyonik** [comment]
> HI @Zibilyonik, 👋
> 
> ### Great job thus far. 🙌 Please see my comments. 👇
> * [x]  You should not merge until your PR is approved.
> 
> * [x]  Link to Heroku is not added to your readME file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/heroku.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
> 
> * [x]  Fix all linter errors.
> 
> **Kindly submit another CRR once these issues have been fixed.** _Happy coding!_ 🎉

The linter errors are from Microverse scaffolding.
Please tell me how I'm supposed to complete the Heroku deployment without pushing the project into the master branch. It even says on the project description that it should be done from the master branch, so I will choose to ignore that request.
The link to Heroku has been added to the project README file.

**Review by kobiyoyo — COMMENTED** [review]
## Hi Team      
#### Great Job so far, but there are a few more things required. 
### General
- [ ] Lets re-open this `PR`
- [ ] Link to Heroku  should be added to your readME file
- [ ] Since its merged i can't detect if you fixed linter errors.
## [OPTIONAL]
- [ ] You can use these articles below
#### Deploy Rails app to heroku
- https://devcenter.heroku.com/articles/getting-started-with-rails6
#### Deploying from a branch besides master
- https://devcenter.heroku.com/articles/git
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by Zibilyonik** [comment]
> ## Hi Team 
> #### Great Job so far, but there are a few more things required.
> ### General
> * [ ]  Lets re-open this `PR`
> * [ ]  Link to Heroku  should be added to your readME file
> * [ ]  Since its merged i can't detect if you fixed linter errors.
> 
> ## [OPTIONAL]
> * [ ]  You can use these articles below
> 
> #### Deploy Rails app to heroku
> * https://devcenter.heroku.com/articles/getting-started-with-rails6
> 
> #### Deploying from a branch besides master
> * https://devcenter.heroku.com/articles/git
> 
> ### Make changes and submit another code review request.
> _Happy coding_
> (Any questions Feel free to contact me on slack @kobiyoyo)

PR doesn't have to be opened. The project instructions specifically say that it should be done from the master branch.

image

Link to Heroku already exists within the master branch's README file.

image

LINTER ERRORS ARE FROM MICROVERSE'S SCAFFOLDING, THEY ARE NOT MY RESPONSIBILITY NOR MY FAULT.
I have mentioned these points multiple times in the previous PR comments yet it seems no code reviewer has the time to read through them.

image

**Pull request merged**
